<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ProxyCage.Core\ProxyCage.Core.csproj" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.8" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>cehoproxy-tray</AssemblyName>
    <AssemblyTitle>CehoProxy</AssemblyTitle>
    <Product>CehoProxy</Product>
    <ApplicationIcon>..\..\assets\cehoproxy.ico</ApplicationIcon>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\cehoproxy.ico" LogicalName="cehoproxy.ico" />
  </ItemGroup>

</Project>
